# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/constructing_projects/FPGA_projects/FPGA_design_course/lab19_MusicPlayer/vivado/music_player.srcs/sources_1/ip/DCM_audio/DCM_audio.xci
# IP: The module: 'DCM_audio' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/constructing_projects/FPGA_projects/FPGA_design_course/lab19_MusicPlayer/vivado/music_player.gen/sources_1/ip/DCM_audio/DCM_audio_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'DCM_audio'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/constructing_projects/FPGA_projects/FPGA_design_course/lab19_MusicPlayer/vivado/music_player.gen/sources_1/ip/DCM_audio/DCM_audio.xdc
# XDC: The top module name and the constraint reference have the same name: 'DCM_audio'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/constructing_projects/FPGA_projects/FPGA_design_course/lab19_MusicPlayer/vivado/music_player.gen/sources_1/ip/DCM_audio/DCM_audio_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'DCM_audio'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: d:/constructing_projects/FPGA_projects/FPGA_design_course/lab19_MusicPlayer/vivado/music_player.srcs/sources_1/ip/DCM_audio/DCM_audio.xci
# IP: The module: 'DCM_audio' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/constructing_projects/FPGA_projects/FPGA_design_course/lab19_MusicPlayer/vivado/music_player.gen/sources_1/ip/DCM_audio/DCM_audio_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'DCM_audio'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/constructing_projects/FPGA_projects/FPGA_design_course/lab19_MusicPlayer/vivado/music_player.gen/sources_1/ip/DCM_audio/DCM_audio.xdc
# XDC: The top module name and the constraint reference have the same name: 'DCM_audio'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/constructing_projects/FPGA_projects/FPGA_design_course/lab19_MusicPlayer/vivado/music_player.gen/sources_1/ip/DCM_audio/DCM_audio_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'DCM_audio'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
